# Generated by Django 5.2.7 on 2025-11-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code de la tâche')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la tâche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duree', models.IntegerField(verbose_name='Durée (en jours)')),
                ('date_debut_tot', models.IntegerField(blank=True, null=True, verbose_name='Date de début au plus tôt')),
                ('date_fin_tot', models.IntegerField(blank=True, null=True, verbose_name='Date de fin au plus tôt')),
                ('date_debut_tard', models.IntegerField(blank=True, null=True, verbose_name='Date de début au plus tard')),
                ('date_fin_tard', models.IntegerField(blank=True, null=True, verbose_name='Date de fin au plus tard')),
                ('marge_totale', models.IntegerField(blank=True, null=True, verbose_name='Marge totale')),
                ('marge_libre', models.IntegerField(blank=True, null=True, verbose_name='Marge libre')),
                ('dependances', models.ManyToManyField(blank=True, related_name='successeurs', to='pert.tache', verbose_name='Dépendances (tâches à terminer avant)')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='pert.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['code'],
                'unique_together': {('projet', 'code')},
            },
        ),
    ]
